server {
    listen 80;

    # /fastapi/ 요청 -> AI 서버로 전달
    location /fastapi {
        proxy_pass http://ai-server:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 메인 요청 -> Node.js로 전달
    location / {
        proxy_pass http://node-app:8080;
        proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
    }
}