name: Node.js SCP Deploy

on:
  push:
    branches: 
      - "main" # main 브랜치에 푸시하면 실행
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t node-backend .

      # 2. 이미지를 tar 파일로 압축 (용량을 줄이기 위해 gzip 사용)
      - name: Save and compress image
        run: docker save node-backend | gzip > node-backend.tar.gz

      # 3. SCP를 이용해 EC2로 압축 파일 전송
      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "node-backend.tar.gz, docker-compose.yml, Dockerfile" # 전송할 파일들
          target: "/home/ubuntu/deploy" # EC2 내 저장 경로

      # 4. EC2에서 이미지 로드 및 실행
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/deploy
            
            # 기존 이미지, 컨테이너 내리기
            sudo docker-compose down
            
            # 압축 파일로부터 이미지 로드
            sudo docker load < node-backend.tar.gz

            # 새로 실행
            sudo docker-compose up -d --force-recreate

            rm node-backend.tar.gz
            sudo docker image prune -f